export const APP_GENERATE_TOKEN_REQUEST = "APP_GENERATE_TOKEN_REQUEST";
export const APP_GENERATE_TOKEN_SUCCESS = "APP_GENERATE_TOKEN_SUCCESS";
export const APP_GENERATE_TOKEN_FAILURE = "APP_GENERATE_TOKEN_FAILURE";



