export const APP_GENERATE_TOKEN_REQUEST = "APP_GENERATE_TOKEN_REQUEST";
export const APP_GENERATE_TOKEN_SUCCESS = "APP_GENERATE_TOKEN_SUCCESS";
export const APP_GENERATE_TOKEN_FAILURE = "APP_GENERATE_TOKEN_FAILURE";
// 
export const APP_SITE_SETTINGS_REQUEST = "APP_SITE_SETTINGS_REQUEST";
export const APP_SITE_SETTINGS_SUCCESS = "APP_SITE_SETTINGS_SUCCESS";
export const APP_SITE_SETTINGS_FAILURE = "APP_SITE_SETTINGS_FAILURE";


export const APP_GET_LANGUAGES_REQUEST = "APP_GET_LANGUAGES_REQUEST";
export const APP_GET_LANGUAGE_SUCCESS = "APP_GET_LANGUAGE_SUCCESS";
export const APP_GET_LANGUAGE_FAILURE = "APP_GET_LANGUAGE_FAILURE";

export const APP_USER_LOGIN_REQUEST = "APP_USER_LOGIN_REQUEST";
export const APP_USER_LOGIN_SUCCESS = "APP_USER_LOGIN_SUCCESS";
export const APP_USER_LOGIN_FAILURE = "APP_USER_LOGIN_FAILURE";

export const APP_USER_SIDE_MENUS_REQUEST = "APP_USER_SIDE_MENUS_REQUEST";
export const APP_USER_SIDE_MENUS_SUCCESS = "APP_USER_SIDE_MENUS_SUCCESS";
export const APP_USER_SIDE_MENUS_FAILURE = "APP_USER_SIDE_MENUS_FAILURE";