export const APP_GENERATE_TOKEN_REQUEST = "APP_GENERATE_TOKEN_REQUEST";
export const APP_GENERATE_TOKEN_SUCCESS = "APP_GENERATE_TOKEN_SUCCESS";
export const APP_GENERATE_TOKEN_FAILURE = "APP_GENERATE_TOKEN_FAILURE";
// 
export const APP_SITE_SETTINGS_REQUEST = "APP_SITE_SETTINGS_REQUEST";
export const APP_SITE_SETTINGS_SUCCESS = "APP_SITE_SETTINGS_SUCCESS";
export const APP_SITE_SETTINGS_FAILURE = "APP_SITE_SETTINGS_FAILURE";


export const APP_GET_LANGUAGES_REQUEST = "APP_GET_LANGUAGES_REQUEST";
export const APP_GET_LANGUAGE_SUCCESS = "APP_GET_LANGUAGE_SUCCESS";
export const APP_GET_LANGUAGE_FAILURE = "APP_GET_LANGUAGE_FAILURE";

export const APP_USER_LOGIN_REQUEST = "APP_USER_LOGIN_REQUEST";
export const APP_USER_LOGIN_SUCCESS = "APP_USER_LOGIN_SUCCESS";
export const APP_USER_LOGIN_FAILURE = "APP_USER_LOGIN_FAILURE";

export const APP_USER_SIDE_MENUS_REQUEST = "APP_USER_SIDE_MENUS_REQUEST";
export const APP_USER_SIDE_MENUS_SUCCESS = "APP_USER_SIDE_MENUS_SUCCESS";
export const APP_USER_SIDE_MENUS_FAILURE = "APP_USER_SIDE_MENUS_FAILURE";

export const APP_USER_HOMEPAGE_REQUEST = "APP_USER_HOMEPAGE_REQUEST";
export const APP_USER_HOMEPAGE_SUCCESS = "APP_USER_HOMEPAGE_SUCCESS";
export const APP_USER_HOMEPAGE_FAILURE = "APP_USER_HOMEPAGE_FAILURE";


export const APP_TAB_MENU_REQUEST = "APP_TAB_MENU_REQUEST";
export const APP_TAB_MENU_SUCCESS = "APP_TAB_MENU_SUCCESS";
export const APP_TAB_MENU_FAILURE = "APP_TAB_MENU_FAILURE";

export const APP_EMPLOYEE_TAB_MENU_REQUEST = "APP_EMPLOYEE_TAB_MENU_REQUEST";
export const APP_EMPLOYEE_TAB_MENU_SUCCESS = "APP_EMPLOYEE_TAB_MENU_SUCCESS";
export const APP_EMPLOYEE_TAB_MENU_FAILURE = "APP_EMPLOYEE_TAB_MENU_FAILURE";

export const APP_LANGUAGE_LIST_REQUEST = "APP_LANGUAGE_LIST_REQUEST";
export const APP_LANGUAGE_LIST_SUCCESS = "APP_LANGUAGE_LIST_SUCCESS";
export const APP_LANGUAGE_LIST_FAILURE = "APP_LANGUAGE_LIST_FAILURE";


export const APP_GET_SETTINGS_MENU_REQUEST = "APP_GET_SETTINGS_MENU_REQUEST";
export const APP_GET_SETTINGS_MENU_SUCCESS = "APP_GET_SETTINGS_MENU_SUCCESS";
export const APP_GET_SETTINGS_MENU_FAILURE = "APP_GET_SETTINGS_MENU_FAILURE";






